### ISSUE TITLE
[Feature request] RMSE and MAE using bins + standardizing benchmarks

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#1]
Currently, it's very hard to compare results [here](https://github.com/open-spaced-repetition/fsrs-vs-sm17/blob/main/README.md) with the results from [the benchmark](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Benchmark).
I recommend the following:
1) Rename the "RMSE" column to "RMSE (raw)"
2) Add two new columns: "RMSE (bins)" and "MAE (bins)"
3) Add a text note: "RMSE (bins) and MAE (bins) are added to allow a comparison between these values and the values on the benchmark page of FSRS wiki"

Also, while it may be too late for that, it would be better to have one repo for all "FSRS vs SuperMemo" comparisons, instead of 2 different repos.

**Comment by L-M-Sherlock** [comment]
> * adding Universal Metric

If we add more algorithms into comparison, it will be infeasible to calculate Universal Metric. Because UM needs pair-comparison. We need to make `n * (n - 1) / 2` pair-comparison when we compare `n` algorithms. It will cost too much time.

> * adding Memrise and SM-2 to https://github.com/open-spaced-repetition/fsrs-benchmark

SM-2 is OK, because it aims to schedule interval with R = 90% as mentioned in Woz's wiki. [Half-Life Regression](https://github.com/duolingo/halflife-regression) of Duolingo is another candidate.

> * replacing the link to https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Benchmark on the Wiki page with the link to https://github.com/open-spaced-repetition/fsrs-benchmark?

Maybe we need to add three links in the wiki page for fsrs-vs-sm15, fsrs-vs-sm17 and fsrs-benchmark.

**Comment by user1823** [comment]
> CLES has to be computed using some numbers. I don't like the idea of a metric that, in turn, is based on another metric, like a metric of a metric. It makes it harder to interpret, and I want to use simple metrics.

But, you yourself proposed using CLES here: https://github.com/open-spaced-repetition/fsrs-benchmark/issues/1#issuecomment-1709456177

But, just like UM, it has a problem that it is calculated for algorithm pairs. So, as Sherlock said, calculation and presentation of the results would be complicated as we add more and more algorithms.

**Comment by Expertium** [comment]
> But, you yourself proposed using CLES here: #1 (comment)

I didn't think it through, my bad.

**Comment by L-M-Sherlock** [comment]
> I don't know much about UM. But, if it requires pair comparison, how do you calculate the UM for the three algorithms on the fsrs-vs-sm17 page? In other words, what is the other algorithm that is used along with each of the three algorithms?

I make three cross comparison among them:

```python
            sm17_by_sm16, sm16_by_sm17 = cross_comparsion(
                revlogs, 'SM16', 'SM17(exp)')
            sm17_by_fsrs, fsrs_by_sm17 = cross_comparsion(
                revlogs, 'FSRS', 'SM17(exp)')
            fsrs_by_sm16, sm16_by_fsrs = cross_comparsion(
                revlogs, 'SM16', 'FSRS')
            result['FSRS']['UniversalMetric'] = (
                fsrs_by_sm17 + fsrs_by_sm16) / 2
            result['SM16']['UniversalMetric'] = (
                sm16_by_sm17 + sm16_by_fsrs) / 2
            result['SM17']['UniversalMetric'] = (
                sm17_by_sm16 + sm17_by_fsrs) / 2
```
source: https://github.com/open-spaced-repetition/fsrs-vs-sm17/blob/abb42ea135d9fd64ca7acdbe7a69477506038163/script.py#L225-L236

> Can you provide a link?

https://supermemopedia.com/index.php?title=Algorithm_SM-17_vs._older_SuperMemos#Algorithm_SM-2

**Comment by user1823** [comment]
> I make three cross comparison among them:

So, you are taking an average of the two UMs for each algorithm. I don't think that this is a good approach because it makes UM hard to interpret. So, I think that we should remove UM from all the comparisons (unless we are comparing only two algorithms).

> https://supermemopedia.com/index.php?title=Algorithm_SM-17_vs._older_SuperMemos#Algorithm_SM-2

It doesn't mention anywhere that SM-2 aims to schedule interval with R = 90%.

**Comment by L-M-Sherlock** [comment]
> It doesn't mention anywhere that SM-2 aims to schedule interval with R = 90%.

It mentions `SInc=1.2+(1-Diff)*2.3` in SM-2. SInc is stability increase. And stability is the interval with R = 90%.

**Comment by user1823** [comment]
> > It doesn't mention anywhere that SM-2 aims to schedule interval with R = 90%.
> 
> It mentions `SInc=1.2+(1-Diff)*2.3` in SM-2. SInc is stability increase. And stability is the interval with R = 90%.

But, it doesn't mention that interval = stability. For example, if all intervals are, say, 1.5 times the stability, SM-2 is scheduling intervals at about 85% retrievability, not 90% retrievability.

> Woz compared SM-17 with SM-2, so it is possible to compare FSRS with SM-2, too.

Yes. But, he didn't reveal how he compared them.

**Comment by Expertium** [comment]
This is just my opinion, but I would exclude algorithms that weren't designed to predict R, such as SM-2.

**Comment by user1823** [comment]
> This is just my opinion, but I would exclude algorithms that weren't designed to predict R, such as SM-2.

In my opinion, the comparison with SM-2 is very important because this comparison is what users would want to know to help them decide whether to switch to FSRS or not. 

If Woz can compare SM-2 with SM-17, we can also compare it with FSRS.

**Comment by L-M-Sherlock** [comment]
https://supermemopedia.com/wiki/Details_about_the_comparison_between_SM-17_and_SM-2

It would take a few days for the answer. So we can do something else first. I have added the link of current repo into the wiki page. After we complete all comparison and evaluation, I plan to re-write the wiki page.

**Comment by user1823** [comment]
> It would take a few days for the answer. So we can do something else first.

Till then, you can
- add Duolingo's Half Life Regression
- remove Universal Metric

@Expertium may have more suggestions.

**Comment by L-M-Sherlock** [comment]
> * remove Universal Metric

I prefer to keep universal metric in fsrs-vs-sm15 and fsrs-vs-sm17, because it's proposed by Woz and I plan to write an email to him with this metric. The benchmark repo will not include it, due to the technical limitation.

**Comment by L-M-Sherlock** [comment]
> In [SuperMemo 18](https://supermemopedia.com/wiki/SuperMemo_18) code you have this:
> 
>  MDC:real; //memory decay constant
>  MDC:=ln(10/9);
> The original algorithm is described [here](https://supermemo.guru/wiki/SuperMemo_1.0_for_DOS_(1987)#Algorithm_SM-2). The term [stability](https://supermemopedia.com/wiki/Stability) was not used then, but [interval](https://supermemopedia.com/wiki/Interval) reflects the concept of [stability](https://supermemopedia.com/wiki/Stability).
> 
> (thank you for working on this, independent code will be helpful to verify claims of SuperMemo)

Pretty fast. My implementation in the old benchmark is correct. I will add SM-2 soon.

**Comment by L-M-Sherlock** [comment]
HLR and SM2 have been added into the benchmark.

**Comment by Expertium** [comment]
> HLR and SM2 have been added into the benchmark.

You forgot to update the "models" section, where you give a brief overview of each algorithm.

@user1823 what so you think about having 2 tables with different weighted averages? I think we should only have one table.

**Comment by L-M-Sherlock** [comment]
> You forgot to update the "models" section, where you give a brief overview of each algorithm.

I will update README tomorrow.

> Also, Sherlock, I know this is a lot of work, but how about doing all of this for fsrs-vs-sm15 and fsrs-vs-sm17? I mean, using the same benchmarking procedure with the same metrics.

I didn't use TimeSeriesSplit in these two repo. And I don't plan to update the comparison method. Do you mean to convert the dataset from SuperMemo into current benchmark?

**Comment by Expertium** [comment]
I meant that I want you to run the same models on SuperMemo data, and display the same metrics.

**Comment by user1823** [comment]
> @user1823 what do you think about having 2 tables with different weighted averages? I think we should only have one table.

I don't have any strong opinions on this. Both approaches (one table or two tables) work fine for me.

I do think that having two tables can sometimes be confusing, especially when the order of performance of the algorithms is different in the two tables.

But, if academic papers often include multiple tables with different weights (as Sherlock said), there should be some reason for that.

**Comment by Expertium** [comment]
> especially when the order of performance of the algorithms is different in the two tables.

Yeah, right now it's unclear whether FSRS v3 is better than LSTM.

I'll check the .csv file later, to see if I can come up with a filter for outliers, maybe that's the issue.

**Comment by Expertium** [comment]
Actually, upon close inspection, it had very little effect in most cases, except for logloss of LSTM, and only when using ln(review). Other numbers changed only a little.
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/04055fe5-43f3-4c60-92b0-5d93ce59ad21)

**Comment by L-M-Sherlock** [comment]
> Yeah, right now it's unclear whether FSRS v3 is better than LSTM.

I guess it depends on the number of reviews. Deep learning model usually needs more data.

> Basically, if all three R-predicting algorithms perform poorly for this user, then it's an outlier.

It's not a good method to filter out the outliers, because the metric is related to the average retention of users: 

> For example, expected metric E(LSD(R=0.5)) is 0.25, while the same expected metric E(LSD(R=0.9)) is just 0.09. For R=0.97, it is only E(LSD(R=0.97))=0.0291.

Source: https://supermemo.guru/wiki/Universal_metric_for_cross-comparison_of_spaced_repetition_algorithms#Expected_penalty_problem

I recommending keeping all data. Most submitters are serious learners. I have removed one data due to inadequate reviews.

By the way, maybe we can draw a graph to show the relation between metrics and the number of reviews.

**Comment by L-M-Sherlock** [comment]
> I meant that I want you to run the same models on SuperMemo data, and display the same metrics.
> All of this, but for SM data

The result of FSRS v4 would be different. Because the implementation of FSRS v4 in fsrs-vs-sm15 and fsrs-vs-sm17 is online learning version. If we use the evaluation method of the benchmark, the different result would also make users confused.

**Comment by Expertium** [comment]
> I guess it depends on the number of reviews. Deep learning model usually needs more data.

I meant that if you look at two tables, LSTM and FSRS v3 have different "places", depending on the weighting system, and it's unclear which one is the second most accurate algorithm, and which one is the third most accurate.
