### ISSUE TITLE
Can we remove d99c0ae from the dataset?

### ISSUE THREAD

**Issue by dae** [open-spaced-repetition/fsrs-benchmark#1]
FSRS4 ignores it, but FSRS-rs creates a file for it, meaning that the file needs to be manually removed to be a fair comparison.

**Comment by L-M-Sherlock** [comment]
OK. I will remove it in the huggingface dataset.

**Comment by L-M-Sherlock** [comment]
Done: https://huggingface.co/datasets/open-spaced-repetition/fsrs-dataset/commit/4a748011ad581fba3dc3fd3d7155db3ed6aece14
