### ISSUE TITLE
Remove collecitons of people who misuse Hard from the calculation of the default parameters

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#121]
We can identify people who misuse Hard based on 2 criteria:
1) Their w_15 is 0, or very close to 0. w_15 controls how much SInc for Hard is different from SInc for Good. If w_15=0 then SInc=1, in other words, no increase in memory stability. This is likely due to the fact they use Hard when they forgot the card.
2) Their RMSE is greater than average, which is currently 5.0% for FSRS-5. Since all metrics are based on the Again=0, Hard/Good/Easy=1 assumption, this is also an indicator that Hard was misused.

So here's what I want you, LMSherlock, to do:
1) Find all collections for which w_15<0.01
2) Among those collections, find collections with RMSE>5.0%
3) Record user ids of those collections that meet both criteria
4) Re-calculate the default parameters while excluding those collections

This will ensure that the default parameters are not affected by the misuses of Hard.

**Comment by L-M-Sherlock** [comment]
The paradox is: if the user misused `hard` when they forgot, they may have a fakely high retention leading to fakely long stability because they would press `hard` in the next review again. So their w_15 may be not very close 0.

**Comment by Expertium** [comment]
Hm. Do you think there is a reliable way to detect whether someone is misusing Hard?

**Comment by brishtibheja** [comment]
I mean hasn't everyone done it a few times at least?

> Do you think there is a reliable way to detect whether someone is misusing Hard?

Just throwing one idea. People who do that knowing they should press **Again**+relearn will have more revlogs that go like 22221. Press **Hard** again and again before you decide to fail the card. Coming from personal experience. Most of my 2 ratings would be followed by a 1 rating. Changed that habit a long time ago though.

**Comment by Expertium** [comment]
> I mean hasn't everyone done it a few times at least?

If someone misused Hard 1% of the time and used it properly 99% of the time, their w_15 will definitely be higher than 0.01. The issue is that, as LMSherlock pointed out, w_15 may paradoxically be high even when the user is misusing Hard.
