### ISSUE TITLE
Add features to the dataset: time (in hours) since 'day_starts_at' and workload of today before current review

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#125]
This issue is a reminder to add the following features to the dataset and make a version of FSRS that can use them:
1) Time (in hours) since 'day_starts_at' when the review happened. If you can't get absolute time (like, for example, 9 AM), relative time like this works too. But absolute time would be better since it doesn't depend on the choice of 'day_starts_at'.
2) The number of reviews done on a given day before the current review. This number: 
![20240929_032720](https://github.com/user-attachments/assets/562d717d-ed0d-4bfd-9302-46d0a13e2494)

I need these features to develop FSRS-6.

**Comment by Expertium** [comment]
Btw, if possible, I'd like you to do it within a month. If the data necessary for developing FSRS-6 is already available and we don't need a new dataset for that, then we could develop it very quickly (as I said elsewhere, I already have the formulas sketched out) and potentially even release it instead of FSRS-5 in Anki 24.10.
As long as I have the data and the optimizer code that takes these 2 new features as inputs (`X[:,0]` is elapsed time, `X[:,1]` is rating, so the new features would be `X[:,2]` and `X[:,3]`), it'll take me a week at most to make FSRS-6 and benchmark it. Then all that's left would be integrating it into Anki.

**Comment by L-M-Sherlock** [comment]
The data: https://drive.google.com/file/d/1q-hu1clVJreoh6Sl90Dlu9WPWMjD6N7u/view?usp=sharing

The code:

https://github.com/open-spaced-repetition/srs-benchmark/blob/2fc9602d96f6e97697e75e405ee6fcfb39612fe4/other.py#L1726-L1738

**Comment by Expertium** [comment]
What about the optimizer code?

**Comment by L-M-Sherlock** [comment]
You can copy the code of "FSRS5" and modify it. I don't know how you will use the new features.

**Comment by Expertium** [comment]
I just need the new features to be available as `X[:,2]` and `X[:,3]`. Also, I don't know how to run it from other.py. Usually I use `set DEV_MODE=1 && python script.py`, but clearly that's not what I need. `set DEV_MODE=1 && python other.py` doesn't specify the model name, so idk

**Comment by L-M-Sherlock** [comment]
You can run `set MODEL=FSRS-fatigue && python other.py` to make the dataset include the new features. But you need to implement FSRS_fatigue by yourself.

**Comment by Expertium** [comment]
Maybe I'm not being clear enough. I will work on the formulas, but in order to do that, first, I need X[:,2] and X[:,3] to be in the optimizer code. Do I not need to change anything? Like, `forward`, for example? Or `build_dataset`?

**Comment by L-M-Sherlock** [comment]
You already have the access to X[:,2] and X[:,3] in the branch of https://github.com/open-spaced-repetition/srs-benchmark/tree/Expt/fatigue

**Comment by Expertium** [comment]
But the optimizer code doesn't need any changes?

**Comment by L-M-Sherlock** [comment]
I have made the change in this commit: https://github.com/open-spaced-repetition/srs-benchmark/commit/2fc9602d96f6e97697e75e405ee6fcfb39612fe4

**Comment by Expertium** [comment]
I mean the **optimizer**, this: https://github.com/open-spaced-repetition/fsrs-optimizer/blob/main/src/fsrs_optimizer/fsrs_optimizer.py

EDIT: I guess I'm dumb, I don't need the code from that repo, other.py has it's own optimizer code

**Comment by Expertium** [comment]
Welp...I was running the benchmark, but then I had to restart my PC. Can you guess what set `set DEV_MODE=1 MODEL=FSRS-fatigue && python other.py` does now, after the restart? That's right, run Ebisu. Can you guess what it does after removing all Ebisu code? Obviously, it runs FSRS v3. Obviously...
I have never managed to successfully run other models using it. I thought today was the first day I will be able to do it, but it somehow got messed up after restarting my PC.

EDIT: ok, I give up. I can't figure out what I'm doing wrong. Jarrett, please make a file with only FSRS-fatigue code, so that there is no way it could possibly be doing anything else.
EDIT 2: ok, so `set DEV_MODE=1 MODEL=FSRS-fatigue && python other.py` runs Ebisu, and `set MODEL=FSRS-fatigue && python other.py` results in `cannot import name 'rmse_matrix' from 'fsrs_optimizer'`. Yeah...
EDIT 3: I deleted all the code from other.py and copied it again from here: https://github.com/open-spaced-repetition/srs-benchmark/blob/2fc9602d96f6e97697e75e405ee6fcfb39612fe4/other.py
Now both `set DEV_MODE=1 MODEL=FSRS-fatigue && python other.py` and `set MODEL=FSRS-fatigue && python other.py` just run Ebisu. Or at least try to, since they can't import it
EDIT 4: I removed all Ebisu code. Now I get `local variable 'model' referenced before assignment` when using either of the two commands.
EDIT 5: ok, maaaaaaaaybe if I find a way to import Ebisu (simply `import ebisu` doesn't work) everything will be fine. Let's try `pip install ebisu`
EDIT 6: Nope, `local variable 'model' referenced before assignment`
EDIT 7: Ok, let's try to remove all this mess, copy-paste from other https://github.com/open-spaced-repetition/srs-benchmark/blob/2fc9602d96f6e97697e75e405ee6fcfb39612fe4/other.py again, and try again
...and I'm back to running FSRS v3. Great
EDIT 8: I replaced "FSRSv3" with "FSRS-fatigue" in `create_features` and in `model_name = os.environ.get`. Let's see...`local variable 'model' referenced before assignment`. With both `set DEV_MODE=1 MODEL=FSRS-fatigue && python other.py` and `set MODEL=FSRS-fatigue && python other.py`

Jarrett, please save me from this hell. Just make a file that doesn't have ANY code other than FSRS-fatigue code. Just make a new optimizer branch so I can run script.py

EDIT 9: I realized why it "worked" before restarting my PC - I was running script.py, not other.py

**Comment by L-M-Sherlock** [comment]
1. `DEV_MODE=1` has no impact on `other.py`. 
2. I guess you set the environment variable incorrectly. Could you print the `model_name`?

**Comment by L-M-Sherlock** [comment]
I updated the branch. Now you can simply run FSRS-fatigue via `set MODEL=FSRS-fatigue && python other.py`. And you can modify the code of FSRS_fatigue to implement your idea.

**Comment by Expertium** [comment]
Nope, I get `local variable 'model' referenced before assignment` again. With this code: https://github.com/open-spaced-repetition/srs-benchmark/blob/Expt/fatigue/other.py
...or `cannot import name 'rmse_matrix' from 'fsrs_optimizer'`. I just tried again and got a different error somehow
Btw, I looks like I've encountered this problem before - the path to the optimizer is some kind of default path, not what I specified in script.py
EDIT: I upgraded 'fsrs_optimizer' using `pip` and now I'm back to `local variable 'model' referenced before assignment`. On the bright side, it somehow fixed the problem with `root_mean_squared_error` not working on my PC (I always had to replace it with `mean_squared_error` and add `squared=False`)
Anyway, right now I'm getting `local variable 'model' referenced before assignment`, and since it doesn't tell me which line of code is causing the problem, I can't investigate it further.

**Comment by L-M-Sherlock** [comment]
Have you pulled the latest code? If so, I don't know why you get `local variable 'model' referenced before assignment` again.

Please to do these steps to pull the latest code:
1. git restore .
2. git pull

If you still meet problems, please contact me via discord.

**Comment by L-M-Sherlock** [comment]
added in https://drive.google.com/file/d/1pOdU5Aw9im9YyfGkWqdkMmf_E_BgOUFc/view?usp=sharing
