### ISSUE TITLE
Add GRU-P-F

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#128]
Currently, all models only use interval lengths and grades. I tried incorporating time of the day and the number of reviews done on that day into FSRS, but it didn't improve results. However, it's possible that a neural network would be able to utilize that information.
Please make GRU-P-F (or whatever you want to call it, I'm not good with names), which will have 4 input features.

**Comment by L-M-Sherlock** [comment]
I'm waiting for the new dataset.

**Comment by Expertium** [comment]
What do you mean?

**Comment by L-M-Sherlock** [comment]
I mean I will re-benchmark everything with the new dataset.

**Comment by Expertium** [comment]
Did Dae say that he will make a new dataset soon?

**Comment by L-M-Sherlock** [comment]
https://github.com/ankitects/anki/pull/3511#issuecomment-2429059085

**Comment by Expertium** [comment]
Oh, I see. I think 20k is better though, I'd prefer not losing accuracy.

**Comment by L-M-Sherlock** [comment]
My disk would complain. And the benchmarking time has been too long.

**Comment by Expertium** [comment]
Will the new dataset have deck names or preset names or both?

**Comment by L-M-Sherlock** [comment]
It includes deck_id and preset_id.
