### ISSUE TITLE
Make a new tiny parquet dataset

### ISSUE THREAD

**Issue by Gilfaro** [open-spaced-repetition/fsrs-benchmark#134]
Currently with the new dataset the framework expects a parquet file as input so the old tiny dataset used for experiments cannot be used anymore.
Make a new tiny dataset as parquet from the new dataset with the same ~10 users covering most of the dataset edge cases and average users.

**Comment by L-M-Sherlock** [comment]
Why not just download the parquet files you need from huggingface? I think it's pretty easy.

**Comment by L-M-Sherlock** [comment]
You can refer to this example:

https://github.com/open-spaced-repetition/anki-revlogs-dataset-builder/blob/main/download_subset.py
