### ISSUE TITLE
I need 3 modifications of Anki 10k

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#136]
1) Vaibhav has an idea how to use real interval lengths for short-term scheduling. However, first I need to develop a formula that fully utilizes fractional interval lengths. So the first dataset that I need is the current Anki 10k, but with interval lengths recalculated from `elapsed_seconds`, such that same-day reviews have an interval length between 0 and 1. Relevant: https://forums.ankiweb.net/t/due-column-changing-days-from-whole-numbers-to-decimals-in-scheduling/52213/6?u=expertium, https://forums.ankiweb.net/t/due-column-changing-days-from-whole-numbers-to-decimals-in-scheduling/52213/12?u=expertium

2) I also want to incorporate sibling reviews into FSRS. Relevant: https://github.com/open-spaced-repetition/srs-benchmark/issues/129#issuecomment-2511152491. I recommend making a new branch of the optimizer, since the optimizer will now need 3 values as inputs: interval length, grade and `sibling_review`.

3) Finally, if both ideas prove to be fruitful, I will need a dataset with *both* intervals lengths as floating point numbers and with the extra data from sibling reviews.

**Comment by L-M-Sherlock** [comment]
For the first modification, it has been implemented:

https://github.com/open-spaced-repetition/srs-benchmark/blob/f49dc94d72ed0e4588b09812d64ac9b58fb76225/other.py#L1980-L1981

> I also want to incorporate sibling reviews into FSRS.

I haven't figured out how to implement it with minimum refactoring. Please wait for a few weeks.

**Comment by L-M-Sherlock** [comment]
I think this issue could be closed?
