### ISSUE TITLE
Updating the benchmark with new data

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#14]
https://github.com/open-spaced-repetition/fsrs4anki/issues/493#issuecomment-1822429421
Now that Dae has provided us with far more data, I'd like you to update the benchmark repo and include the following algorithms:
1) FSRS v4.5 (after we figure out whether the extra parameters are worth using or not)
2) FSRS v4
3) FSRS v4 (dry run)
4) FSRS v3
5) LSTM
6) HLR
7) SM-2
8) Ebisu (once you figure out the details with the dev)

LSTM (short-term) is optional IMO. I'm planning to make a reddit post, and I will need those 8 algorithms. Since benchmarking will take a lot more CPU time now, I can also help you to speed it up by doing some of it myself, if you want me to. Also, please make the dataset downloadable using the `python download_data.py` command, I want to re-do my test of button usage and RMSE.

**Comment by Expertium** [comment]
Also, I would like you to benchmark FSRS v4.5 against SM-17 in the respective repo.

**Comment by L-M-Sherlock** [comment]
The new dataset has 1.5 billions of revlogs as least. It will take a lot of time to benchmark.

**Comment by Expertium** [comment]
Wow. I thought it would be 100-400 million.

**Comment by Expertium** [comment]
Out of curiosity, what are your PC specs?
Also, if you make the dataset downloadable, I can do some benchmarking on my own and report the results, to speed things up a little bit.

**Comment by dae** [comment]
You can use a subset if you wish. I provided that much so you can do longer tests when required, or divide the sample set up to see how different samples differ.

**Comment by L-M-Sherlock** [comment]
> Out of curiosity, what are your PC specs?

Mac M2 MAX 96GB unified memory

**Comment by L-M-Sherlock** [comment]
I'm trying to find an efficient method to deal with the dataset.

**Comment by L-M-Sherlock** [comment]
The converted dataset file:
https://drive.google.com/file/d/1Tg8WmLHxK_VRxnAtATXS_HYdywsaxTyf/view?usp=drive_link

The new benchmark code:
https://github.com/open-spaced-repetition/fsrs-benchmark/tree/Feat/new-dataset

I'm benchmarking FSRSv4.

**Comment by Expertium** [comment]
Once you benchmark it, can you send me a file with RMSE values, as well as % of button usage for each user? I want to re-do my analysis of how button usage affects RMSE.

**Comment by Expertium** [comment]
I tried `git clone https://github.com/open-spaced-repetition/fsrs-benchmark/tree/Feat/new-dataset.git`, I got an error saying that the repository was not found.

**Comment by L-M-Sherlock** [comment]
> I got an error saying that the repository was not found.

You need to clone the fsrs-benchmark repo and checkout the Feat/new-dataset branch.

https://www.atlassian.com/git/tutorials/using-branches/git-checkout

**Comment by Expertium** [comment]
I cloned it some time ago, but I can't figure out the checkout stuff.

**Comment by L-M-Sherlock** [comment]
I recommend installing GitHub Desktop: https://desktop.github.com/, where you can checkout the branch conveniently:

<img width="586" alt="image" src="https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/cf6542e7-05bd-448e-ab05-87b83efd05ad">

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/ab22d2b9-7e97-49b8-abce-cb897d95bd4c)
Ok, what next? How do I run the benchmark?

**Comment by L-M-Sherlock** [comment]
For example:

`MODEL=SM2 & python other.py`

**Comment by Expertium** [comment]
Sorry, but I'm afraid you will have to be very patient with me. Explain the setup process to me as if I was a 45 year old housewife.
1) Where do I unzip the dataset after downloading it? I don't see a folder for it.
2) I don't see the `new-dataset` branch on my PC. Do I need to clone it somehow? If so, how to do it using Github Desktop?
3) Where do I input the code you gave above? I tried this:
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/6ec5ead7-9493-41f6-8d32-e7729dfef887)
But that doesn't seem to work.

**Comment by L-M-Sherlock** [comment]
> 1. Where do I unzip the dataset after downloading it? I don't see a folder for it.

You need to unzip the dataset.7z and move the directory `dataset` to `fsrs-benchmark/`.

> 2\. I don't see the `new-dataset` branch on my PC.

Could you expand this menu?

<img width="646" alt="image" src="https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/a4615707-c8b1-4ad4-872a-011f79c36013">

> 3\. Where do I input the code you gave above? I tried this:

You need to open a terminal, and cd `fsrs-benchmark`, and then you can input the command.

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/8e5ddb00-16ba-42bd-8212-77f57fd541f7)
As far as I can tell, switching to a different branch doesn't affect any files on my PC.

**Comment by Expertium** [comment]
> You need to open a terminal, and cd `fsrs-benchmark`, and then you can input the command.

I get a "'MODEL' is not recognized as an internal or external command, operable program or batch file." error. But it still runs though.

**Comment by Expertium** [comment]
And I'm getting the same issue I had before, with graphs popping up.
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/8007affc-b672-4ea6-8679-821142a181ee)
Unfortunately, I don't remember what code in which file was responsible for this.
EDIT: it's utils.py, I fixed it.

**Comment by L-M-Sherlock** [comment]
> I get a "'MODEL' is not recognized as an internal or external command

Sorry, I forget that you used windows. It should be `set MODEL=SM2`. You can replaced SM2 with `LSTM`, `FSRSv3`, `HLR`.

**Comment by L-M-Sherlock** [comment]
> switching to a different branch doesn't affect any files on my PC.

It does. It can change the contents of script.py and other.py.

**Comment by Expertium** [comment]
> > switching to a different branch doesn't affect any files on my PC.
> 
> It does. It can change the contents of script.py and other.py.

My bad. I tried switching back and forth and checking whether "Date modified" of script.py and other.py changes, and yes, it does.

> It should be `set MODEL=SM2`

Thank you, that works. But I see stuff like this:
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/be386835-eabe-446c-9687-a96687d2e83a)

Even though there are no files with that name, or any .tsv files for that matter.

**Comment by Expertium** [comment]
> EDIT: it's utils.py, I fixed it.

Strange. Last time I fixed that issue by editing utils.py, but not this time.

**Comment by L-M-Sherlock** [comment]
Did you remove the old dataset?

**Comment by Expertium** [comment]
The fsrs-benchmark folder only has the new dataset.

**Comment by Expertium** [comment]
Ah, I see the problem. I have two fsrs-benchmark folders, the previous clone and the new one. Though that still doesn't explain the problem with graphs popping up, since I commented out graphing in **both** utils.py files.
Ok, I'll leave the benchmarking to you. This is giving me a headache.

**Comment by Expertium** [comment]
And please don't forget https://github.com/open-spaced-repetition/fsrs-benchmark/issues/14#issuecomment-1829385739

**Comment by L-M-Sherlock** [comment]
My computer crashed twice. It cost 30 hours to run the benchmark for FSRSv4:

```
Model: FSRSv4
Total number of users: 19934
Total number of reviews: 738181395
metric: LogLoss
FSRSv4 mean: 0.3658
metric: RMSE
FSRSv4 mean: 0.3141
metric: RMSE(bins)
FSRSv4 mean: 0.0818
weights: [0.6774, 1.6889, 4.4659, 15.0454, 4.9454, 1.0627, 0.8762, 0.0464, 1.5597, 0.1358, 0.994, 2.1661, 0.0681, 0.3403, 1.2845, 0.2573, 2.7212]
```

[usage.csv](https://github.com/open-spaced-repetition/fsrs-benchmark/files/13498636/usage.csv)

**Comment by Expertium** [comment]
Thank you! Will you update the results with values weighted by reviews an ln(reviews)?

**Comment by Expertium** [comment]
Also, it says there are around 700 million reviews, not 1.5 billion. Why?

**Comment by L-M-Sherlock** [comment]
> Also, it says there are around 700 million reviews, not 1.5 billion. Why?

The 1.5 billion include short-term reviews.

> Thank you! Will you update the results with values weighted by reviews an ln(reviews)?

I use median by user.

**Comment by Expertium** [comment]
> > Thank you! Will you update the results with values weighted by reviews an ln(reviews)?
> 
> I use median by user.

I meant this:
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/318cd85a-2575-4af8-a608-14467a07ee4d)

**Comment by Expertium** [comment]
> FSRSv4 mean: 0.0818

Also, this is unexpected. It's almost 2x higher than with the old benchmark.

**Comment by L-M-Sherlock** [comment]
> I meant this:

The above metrics are weighted by ln(review).

**Comment by Expertium** [comment]
Then for the sake of consistency, include weighting by n_reviews too, to make everything the same as in the old benchmark.

**Comment by Expertium** [comment]
The same goes for all other algorithms too. Speaking of which, I would love to see a dry run with the new default parameters.

**Comment by L-M-Sherlock** [comment]
```
Model: FSRSv4
Total number of users: 19934
Total number of reviews: 738181395
metric: LogLoss
FSRSv4 mean: 0.3360
metric: RMSE
FSRSv4 mean: 0.3002
metric: RMSE(bins)
FSRSv4 mean: 0.0590
```

**Comment by Expertium** [comment]
I've been trying to run the benchmark myself and this is the new error I get
Commands:
```
cd fsrs-benchmark
set DEV_MODE=1 && set MODEL=SM2 && python other.py
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\Andrew\fsrs-benchmark\other.py", line 674, in <module>
    if file.stem in map(lambda x: x.stem, Path(f"result/{model}").iterdir()):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'result\\SM2 '
```
C:\Users\Andrew\fsrs-benchmark\result\SM2 is a valid path, so idk what's the problem.

**Comment by Expertium** [comment]
I did manage to make script.py work, but not other.py.
Well, at least it means I can benchmark my ideas on the new dataset in the future.

**Comment by Expertium** [comment]
Please add FSRS v4 (dry run) to the benchmark with the new dataset too.

**Comment by L-M-Sherlock** [comment]
> Please add FSRS v4 (dry run) to the benchmark with the new dataset too.

Which initial parameters should the dry run use?

**Comment by Expertium** [comment]
These: https://github.com/open-spaced-repetition/fsrs-benchmark/issues/14#issuecomment-1831523655

Also, share them with Dae so that he will add them to Anki 23.12.

**Comment by Expertium** [comment]
Actually, I'm not sure which parameters built-in FSRS should use
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/61d58bc2-7c44-4ecd-8de1-104c25319d85)

**Comment by L-M-Sherlock** [comment]
The dry run's result has been out.

Total number of users: 19995

Total number of reviews for evaluation: 738,221,150

### Weighted by number of reviews

| Algorithm | Log Loss | RMSE | RMSE(bins) |
| --- | --- | --- | --- |
| FSRS v4 | 0.3360 | 0.3002 | 0.0590 |
| FSRS rs | 0.3404 | 0.3018 | 0.0628 |
| LSTM | 0.4000 | 0.3123 | 0.0859 |
| FSRS v4 (unoptimized) | 0.3677 | 0.3128 | 0.0886 |
| FSRS v3 | 0.4286 | 0.3226 | 0.1074 |
| SM2 | 0.6339 | 0.3592 | 0.1799 |
| HLR | 0.8175 | 0.3790 | 0.2094 |

### Weighted by ln(number of reviews)

| Algorithm | Log Loss | RMSE | RMSE(bins) |
| --- | --- | --- | --- |
| FSRS v4 | 0.3658 | 0.3141 | 0.0820 |
| FSRS rs | 0.3705 | 0.3161 | 0.0860 |
| FSRS v4 (unoptimized) | 0.4023 | 0.3313 | 0.1155 |
| FSRS v3 | 0.5201 | 0.3471 | 0.1425 |
| LSTM | 0.5645 | 0.3562 | 0.1536 |
| SM2 | 0.8702 | 0.3954 | 0.2240 |
| HLR | 2.3669 | 0.5393 | 0.4096 |

---

However, the new median weights will schedule a longer interval (4 days) for new card pressed good in the first time. I'm afraid that it will induce more confusion.

**Comment by Expertium** [comment]
@L-M-Sherlock @user1823 I made a reddit post about the new benchmark: https://www.reddit.com/r/Anki/comments/18csuer/fsrs_is_now_the_most_accurate_spaced_repetition/
I suggest removing the links to my previous posts from wiki, and adding a link to this post instead.

**Comment by user1823** [comment]
> However, the new median weights will schedule a longer interval (4 days) for new card pressed good in the first time. I'm afraid that it will induce more confusion.

But, they are based on a very large number of collections and should be more accurate. I think accuracy is more important. We can tell people that short early intervals is a shortcoming of SM-2, which FSRS has corrected.

Also see Q10 in https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ

**Comment by Expertium** [comment]
I agree with user1823. Built-in FSRS should use the new, more accurate default parameters.

**Comment by L-M-Sherlock** [comment]
OK. I will update the default parameters tomorrow. Maybe I should also draw a distribution graph for the first four parameters.

**Comment by Expertium** [comment]
Btw, I don't think there are any use cases for the old (small) dataset now, so I suggest making the new-dataset branch the main branch.

**Comment by L-M-Sherlock** [comment]
![weight0](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/dd8523e9-fd20-43b7-bf73-d2acb40d0379)
![weight1](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/e8363e70-04ca-46f6-be4d-5d0bab28ce4e)
![weight2](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/f0f17de2-23ec-49c3-865d-f53884aff4d2)
![weight3](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/e1d85bce-0164-4d04-8f8d-8943ab10c9fd)
