### ISSUE TITLE
Determining the effectiveness of the algorithm with default parameters

### ISSUE THREAD

**Issue by logantgt** [open-spaced-repetition/fsrs-benchmark#2]
At the moment I'm trying to build an embedded system which functions like a dedicated physical Anki tool, but with several constraints - for instance, since it'll be running on portable embedded hardware, decks would only be synced to the application (and device) every once in a while, and I don't have the ability to optimize on the device itself, so it's very possible that the default FSRS parameters would never be updated, given an interface for doing so were even provided.

How effective would this be? Assuming its default parameters, how much less efficient might the learning process be as opposed to optimizing every few thousand review logs? How does this outcome compare to SM-2 for example? How do we model this?

**Comment by L-M-Sherlock** [comment]
I will run a benchmark for the default weight soon.

**Comment by L-M-Sherlock** [comment]
| Algorithm | Log Loss | RMSE | RMSE(bins) |
| --- | --- | --- | --- |
| FSRS v4 | 0.3830 | 0.3311 | 0.0543 |
| FSRS v4 (default w) | 0.4280 | 0.3530 | 0.1047 |
| FSRS v3 | 0.5132 | 0.3670 | 0.1326 |
| LSTM | 0.5788 | 0.3752 | 0.1385 |
| SM2 | 0.8847 | 0.4131 | 0.2185 |
| HLR | 2.5175 | 0.5574 | 0.4141 |

The default weight is good enough.

**Comment by logantgt** [comment]
Thank you for taking the time! This is all I needed so I'll close the issue, it may be helpful to others to publish this info in a more accessible area like the benchmark readme. Very promising.
