### ISSUE TITLE
[Feature Request] Add a Transformer

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#23]
This isn't high priority at all, of course, but I would like to see how well a Transformer neural network can perform.
Slightly unrelated, but please add the number of parameters used by LSTM to the description.
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/9148cc9d-9437-448b-9f73-8e0bb38160af)
Also, ideally, the number of parameters in LSTM and in the Transformer should be roughly the same to make the comparison fair and clearly see how much the difference in architecture matters.

**Comment by L-M-Sherlock** [comment]
Transformer has many different implementations and hyperparameters. And it's mainly used for NLP, instead of common time-series prediction. I don't know what's the best practice for our case.

**Comment by Expertium** [comment]
How about a bidirectional LSTM? According to pytorch documentation, it's very easy to do, there is a hyperparameter for that.

**Comment by L-M-Sherlock** [comment]
I try to add the code of transformer: https://github.com/open-spaced-repetition/fsrs-benchmark/commit/480158356f10b72a67201dd86eef93f45bfa0972

But the training is very slow. Maybe I will train the transformer in the next month.

**Comment by Expertium** [comment]
Btw, to make the results comparable ensure that the transformer has roughly the same number of parameters as the LSTM.

**Comment by L-M-Sherlock** [comment]
It only has 492 parameters.

**Comment by Expertium** [comment]
Yes. So the transformer should have around 500. If the transformer has much more parameters, it will be impossible to tell whether RMSE is different because there are more parameters or because the architecture is different. By making the number of parameters more or less the same, we can see how much the architecture matters.

**Comment by L-M-Sherlock** [comment]
I mean my current implementation of transformer has 492 parameters. But I forget how many parameters the LSTM has.

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/59c302ff-6278-4f1c-9d9d-aaeea3ec3ef7)

**Comment by L-M-Sherlock** [comment]
OK. Now their sizes of parameters are very close.

**Comment by Expertium** [comment]
@L-M-Sherlock just a reminder to start working on this

**Comment by L-M-Sherlock** [comment]
> just a reminder to start working on this

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/704f7441-73ef-41b3-9e64-3ce324ae37f4)

I have. But it's too slow and run out of my CPU.

**Comment by L-M-Sherlock** [comment]
Progress: 50%

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/2799a8ec-7054-4fc3-bfff-f817ff276a74)

It's worse than LSTM. It's not surprised. Here is a related work: [Are Transformers Effective for Time Series Forecasting?
](https://ar5iv.labs.arxiv.org/html/2205.13504)

**Comment by Expertium** [comment]
Interesting, I'll take a look at the article later.

**Comment by Expertium** [comment]
What is this?
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/e1cf71b7-5b63-4036-b282-208420d13f1d)

**Comment by L-M-Sherlock** [comment]
> What is this?

It sets the size at 1 for each collection.
