### ISSUE TITLE
collect bad cases from Anki users' dataset

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-benchmark#24]

**Comment by L-M-Sherlock** [comment]
# Bad case 1: very low initial stability

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/8937b865-37fc-40bd-bed0-f11786c20423)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/5212a29f-1787-4797-9282-f2fb6f95cb10)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/c967fd7f-30e9-4712-b1c3-765a507b3b1a)

Solution: decrease the lower limit of w[0], w[1], w[2] and w[3] from 0.1 to 0.01.

**Comment by L-M-Sherlock** [comment]
# Bad case 2: very long elapsed days for first reviews

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/e4fb0d91-7c00-4a1c-bc95-04fb85147d8d)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/3dc0197a-0e15-4d08-83f7-ceeff130de8c)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/5676a774-e49a-47f7-8108-4549539f7faa)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/6c64e7b8-30f5-46be-97d2-4498a267ac6d)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/d0d15ca0-0c68-4753-a206-ca61d9e64681)


Solution: filter out reviews with delta_t > 100.

**Comment by L-M-Sherlock** [comment]
# Bad case 3: non-monotonous initial stability

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/10217f4a-7613-4b01-b0df-f642d4231ce1)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/50e60892-da77-4417-9ba2-e0dbf1d1b686)

The user's initial stability of `good` is lower than the initial stability of `hard`. And the data is enough.

Solution: don't compare initial stability with each other when the number of reviews is enough.

**Comment by Expertium** [comment]
So do you think we should allow S0 to be non-monotonous? I think we shouldn't - users will be confused if, for example, their Easy interval is shorter than their Good interval.

**Comment by L-M-Sherlock** [comment]
It doesn't affect most users. And it could improve the accuracy of affected users significantly.

**Comment by Expertium** [comment]
I think the confusion outweighs any accuracy benefits. @user1823, what do you think?

**Comment by user1823** [comment]
> Solution: don't compare initial stability with each other when the number of reviews is enough.

Just like Expertium, I don't think that it is a good idea because interval for `Good` being less than `Hard` (or any other pair) would not be acceptable.

I think that in this case, the user has two (or more) different types of cards. So, more accurate parameters can be obtained if the user generates different parameters for different types of cards.

**Comment by Expertium** [comment]
> Solution: filter out reviews with delta_t > 100.

I agree that this makes sense for Again, Hard and Good, but probably not for Easy. For Easy, the limit should be higher. Perhaps 365 days?

**Comment by L-M-Sherlock** [comment]
OK. I reverted the solution of bad case 3 and relaxed the filter for bad case 1.
