### ISSUE TITLE
visualize metrics over time

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-benchmark#25]

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/eefdf1c3-093f-4c20-ae13-b338e4f3e47e)

@Expertium, I find that the new parameter is not always better than the old one.

**Comment by user1823** [comment]
IIRC, fsrs-rs uses some type of randomization when gathering/grouping revlogs for optimization. Perhaps that is the issue.
