### ISSUE TITLE
[Feature Request] Add a BiLSTM

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#47]
Here's my code: 
[biLSTM.zip](https://github.com/open-spaced-repetition/fsrs-benchmark/files/14196366/biLSTM.zip)

It's basically other.py, but you don't need to specify the model, just run `set DEV_MODE=1 && python biLSTM.py`. I removed other algorithms and changed `class LSTM`. The problem is - I don't get any errors, but I don't get any output files either. You said that it could be a RAM issue, but I tried setting `n_hidden` to 1 and still got no output. Since there are no errors, I found it hard to debug. So I want you to do 2 things:
1) Find out what's the problem with my code
2) Benchmark the bi-directional LSTM and add it to the table

**Comment by Expertium** [comment]
Ok, I found the issue and fixed it. Of course, you will have to add it to the new, refactored other.py. Note that `n_hidden` is different, the other hyperparameters are the same.
[biLSTM.zip](https://github.com/open-spaced-repetition/fsrs-benchmark/files/14200545/biLSTM.zip)

~~Btw, it seems like it performs worse than LSTM, which is strange~~. Actually, no, it's probably because I'm using the old version of other.py, before you changed it. Well, it should be fairly straightforward to add BiLSTM to the new other.py.

**Comment by L-M-Sherlock** [comment]
I don't want to add more universal models (with a lot of parameters) to the benchmark. The increment in time cost has been a nightmare for me.
