### ISSUE TITLE
Inconsistency in the description

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#5]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/2d89222e-9daf-4b14-b6ce-c4c3b024b842)
The description says that there are 72 collections and 6240084 reviews, but the actual dataset has 71 collections and 4632965 reviews.

**Comment by L-M-Sherlock** [comment]
I removed a collection because #1.

**Comment by Expertium** [comment]
Ok. I suggest editing the description.
