### ISSUE TITLE
[Documentation] The table in readme says "FSRS rs", but there is no description of it

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#6]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/1355dda5-5b6c-4d58-9a3d-6c1d52e0ec6c)
There is no mention of Rust-based FSRS under "Models"
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/2926a199-1d89-40b9-a9d6-2c432bfca791)

**Comment by Expertium** [comment]
One more minor nitpick
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/8f1629a9-9992-47de-b1c0-488e083fd594)
The link to fsrs-rs is in the wrong place; FSRS rs is not related to LSTM, but the link makes it seem that way.

**Comment by L-M-Sherlock** [comment]
Fixed in 5d18131974a1937baf0dc4f547a664e0caa461e9
