### ISSUE TITLE
Add Memrise to the comparison

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#7]
It's not very important, but I do want to see how well (or, rather, how poorly) it performs.
https://memrise.zendesk.com/hc/en-us/articles/360015889057-How-does-the-spaced-repetition-system-work-
Next review in: 4 hours > 12 hours > 24 hours > 6 days > 12 days > 48 days > 96 days > 180 days.
My ancient python code:

```
def memrise(history):
    ivl = 0
    reps = 0
    for delta_t, rating in history:
        delta_t = delta_t.item()
        rating = rating.item() + 1
        intervals = [1, 6, 12, 24, 48, 96, 180]
        if rating > 1:
            reps += 1
            if reps > 7:
                reps = 7
            ivl = intervals[reps-1]
        else:
            ivl = 1
            reps = 1
    return ivl

dataset['memrise_interval'] = dataset['tensor'].map(memrise)
dataset['memrise_p'] = np.exp(np.log(0.9) * dataset['delta_t'] / dataset['memrise_interval'])
```

The obvious issue is that it's unclear what retention level it aims for. I guess we should use 90%. I tried searching for anything that could give me a hint, but found nothing. Btw, what about HLR? I don't know what % it aims for.
As for description, you can add something like: "Memrise, the algorithm used by a language learning app Memrise.".

**Comment by L-M-Sherlock** [comment]
I have forgotten the reason why I removed Memorise. But I think it is not very useful to include it in the benchmark.

**Comment by Expertium** [comment]
Ok. I just wanted to include as many algorithms as possible.

**Comment by Expertium** [comment]
By the way, I wonder what spaced repetition algorithms are used most often, aside from Anki's variation of SM-2. Ideally, we should include many popular algorithms, or at least the ones that are open-source.

**Comment by L-M-Sherlock** [comment]
Here are some SRS: https://notes.andymatuschak.org/Spaced_repetition_memory_system

**Comment by Expertium** [comment]
So Mnemosyne uses a variation of SM-2 as well.
Remnote seems to have a proprietary algorithm.
This article says that Quizlet used logistic regression, but that's about the only useful piece of info: https://quizlet.com/blog/spaced-repetition-for-all-cognitive-science-meets-big-data-in-a-procrastinating-world
