### ISSUE TITLE
[Question] Some more details from a ML perspective

### ISSUE THREAD

**Issue by lars76** [open-spaced-repetition/fsrs-benchmark#86]
Hey, first of all thank you for the dataset. I was wondering if you could provide some more details for people who want to train their own ML algorithms but might not be familiar with the internals of Anki.

Let me see if I understand the dataset correctly:
- The dataset consists of n * m time series where n are the number of users and m are the number of cards.
- Each time series has 3 features: days between last review, rating 1-4, current number of reviews

What is the target variable? And how are you handling the time series for RNNs?

**Comment by L-M-Sherlock** [comment]
The training process is very similar to GPT's next token prediction. Assuming you have 10 reviews belonging to the same cards, the optimizer will train FSRS in the 1st review and treat 2nd review as the target. Then 1-2 reviews are used as the feature and the 3rd review is the target, and so on.

**Comment by lars76** [comment]
I am still not 100% sure, maybe I can give an example.

```
card_id,review_th,delta_t,rating
6,22,-1,1
6,24,0,1
6,27,0,3
6,38,0,3
6,103,2,3
6,201,4,1
```

Let us say we simplify the rating from 2,3,4 to 1 and from 1 (again) to 0.

time series: [0 0 1 1 1 0]

Then the RNN could predict 0.8 as the next token. However, how do you know the number of days this 0.8 corresponds to?

Or are you converting delta_t to absolute days? Then let the RNN predict t+k tokens. Each k corresponds to a single day. Then we know the number of days for rescheduling?

**Comment by L-M-Sherlock** [comment]
> time series: [0 0 1 1 1 0]

The real time series is [(0, 0), (2, 1), (4, 0)] because the short-term reviews are removed in current model.

https://github.com/open-spaced-repetition/srs-benchmark/blob/51c6021ffe18143785f115ef3a097aa7ed484eb6/other.py#L1051-L1057

The RNN doesn't predict the probability of recall directly. It outputs the stability, and the last delta_t will be used to calculate the probability.

For example, [(0, 0), (2, 1)] are the inputs of RNN, and then RNN will output the stability, e.g. 5. The last delta_t 4 and the predicted stability 5 are used to calculate the probability in the forgetting_curve function.

**Comment by lars76** [comment]
Thank you, this makes it much clearer. Have you also tried directly modelling the problem without relying on this curve?

**Comment by L-M-Sherlock** [comment]
The DASH-series models can predict the probability directly.

https://github.com/open-spaced-repetition/srs-benchmark/blob/51c6021ffe18143785f115ef3a097aa7ed484eb6/other.py#L1020-L1029

**Comment by L-M-Sherlock** [comment]
> Have you also tried directly modelling the problem without relying on this curve?

Without the curve, the general model like RNN, LSTM and GRU may make some weird predictions. For example, the forgetting curve generated from them would not decay over time.

**Comment by lars76** [comment]
Thank you for the information. I think a lot of feature engineering has to be done to get good results with direct modelling. For example, grouping similar users or cards. And then having only a single model. I will also do some experiments.

However, it would be easier for evaluating the performance by splitting the scripts some more. For datasets such as COCO, you have a single training and test dataset. You could just create a script that takes as input a single prediction csv file and outputs the metrics (like at Kaggle). While it is good to have a cross validation split, people might use different splits for their training.

**Comment by L-M-Sherlock** [comment]
Our benchmark doesn't have cross validation split. It only uses time-series-split to avoid data leakage.
