### ISSUE TITLE
[Question] Why does HLR perform so poorly?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-benchmark#9]
I tried reading [this code](https://github.com/duolingo/halflife-regression/blob/master/experiment.py), and while I don't really understand how it works, it seems that there is some sort of training procedure. So I'm surprised that it performs about as poorly as SM-2.

**Comment by L-M-Sherlock** [comment]
The paper by Duolingo defined the probability of recall in a different way. In that paper, P(recall) = the number of correct response / the number of review for the same words. Because Duolingo schedules the same word multiple times in the same review sessions.

**Comment by Expertium** [comment]
So they basically defined it as retention.
Can you explain what HLR does when you run it on Anki data?

**Comment by L-M-Sherlock** [comment]
Here is the code: https://github.com/open-spaced-repetition/fsrs-benchmark/blob/main/other.py

The model of HLR is very simple. And it doesn't consider the time-series information.

**Comment by Expertium** [comment]
self.fc = nn.Linear(self.n_hidden, self.n_out)

What does this code do?

**Comment by L-M-Sherlock** [comment]
You can read the document here: https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

**Comment by Expertium** [comment]
So it just does some linear transformation of delta_t and grade, without taking into account their past values, is that correct?

**Comment by L-M-Sherlock** [comment]
You can see the paper:

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/947f33e1-bdbe-48b5-9e6f-419222b357a8)

![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/32575846/89481c87-a262-4a10-9592-605d840934a2)

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/35c1ef7c-4729-4f53-b9b9-06e062a8481d)
How would this work with Anki?
EDIT: I'm just thinking that perhaps HLR works better for Duolingo because they can utilize this info.

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/285f3526-d64d-47c6-b26b-36d5b67d8c39)
![image](https://github.com/open-spaced-repetition/fsrs-benchmark/assets/83031600/43e3e1fa-a253-4325-b334-549a9c515290)

Also, it seems that they just assumed that the intervals given by Leitner and Pimsleur correspond to p=0.5. This doesn't sound like a reasonable assumption to me, but I have an idea. For algorithms such as Memrise, Leitner, Pimsleur, etc. that don't predict R, how about we convert their intervals into stabilities but try several different values of R that S corresponds to?
For SM-2, we just assumed that the intervals correspond to R=90%. For Memrise, we could try 80%, 85%, 90%, 95%, and see which one provides a better fit, and use that in the benchmark. But that has another downside: it could artificially make RMSE and other metrics look better since we are deliberately selecting a value that provides the best fit to our data.
EDIT: just to make it more clear what I mean, suppose we have an algorithm that doesn't predict R. We treat the intervals given by that algorithm as stabilities and then convert them to R using the following formula: `np.exp(np.log(0.9) * testset["delta_t"] / testset["stability"])`. But instead of just using 0.9 in that formula, we try several different values (between 0.7 and 0.95) and see which one results in a lower RMSE, select that value, and use it in the benchmark. But again, that could make the results look better than they really should.

**Comment by L-M-Sherlock** [comment]
> How would this work with Anki?
> EDIT: I'm just thinking that perhaps HLR works better for Duolingo because they can utilize this info.

It's impossible for a single user. Duolingo users learn the same set of vocabulary, so it works for them.

**Comment by L-M-Sherlock** [comment]
> For algorithms such as Memrise, Leitner, Pimsleur, etc. that don't predict R, how about we convert their intervals into stabilities but try several different values of R that S corresponds to?

It sounds like hindsight. It will make the comparison unfair.

**Comment by Expertium** [comment]
> It's impossible for a single user. Duolingo users learn the same set of vocabulary, so it works for them.

I just remembered this old issue. Doesn't this mean that including HLR in the benchmark is meaningless? I mean, if the Duolingo implementation uses extra information and your implementation doesn't, it means that they are essentially two different algorithms.

**Comment by L-M-Sherlock** [comment]
> Duolingo implementation uses extra information and your implementation doesn't

In Duolingo's paper, the HLR has some variants. In our case, it is the variant which doesn't require content-related feature.
